vich_uploader:
    db_driver: orm
    mappings:
        artist_request_picture:
            uri_prefix: /uploads/artist_requests
            upload_destination: '%kernel.project_dir%/public/uploads/artist_requests'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        artist_picture:
            uri_prefix: /uploads/artists
            upload_destination: '%kernel.project_dir%/public/uploads/artists'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
